#!/usr/bin/env bash
FOUND_CC=""

case "$VICEROYARCH" in
  amd64)
    CC="x86_64-apple-darwin20.2-clang"
    ;;
  arm64)
    FOUND_CC="arm64-apple-darwin20.2-clang"
    ;;
  *)
    echo "fatal: unsupported \$VICEROYARCH $VICEROYARCH for darwin. Must be one of: amd64, arm64" >&2
    exit 1
    ;;
esac

export LD_LIBRARY_PATH="/usr/osxcross/lib:$LD_LIBRARY_PATH"
exec "$FOUND_CC" "$@"
