name: Container
on:
  pull_request:
    branches:
    - main
  push:
    tags:
      - 'v*'
jobs:
  build-arm64:
    name: Build ARM64 Container
    runs-on: [Linux, ARM64]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Bake ARM64 container
      run: |
        export OSXCROSS_SDK_URL=${{ secrets.OSXCROSS_SDK_URL }}
        docker buildx bake viceroy-arm64

  build-amd64:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bake AMD64 container
        run: |
          export OSXCROSS_SDK_URL=${{ secrets.OSXCROSS_SDK_URL }}
          docker buildx bake viceroy-amd64
